# Supervised classification

In the data.csv there are letters (uppercases and lowercases) and numbers, 28x28 pixels in a row format.

* First, you need to know which labels are which, meaning you need to visualize some data to realize which number labels represents a letter, or a number.

In [6]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

import matplotlib.pyplot as plt

plt.style.use('dark_background')

pd.set_option('display.max_columns', None)

In [7]:
# Your code here
data = pd.read_csv('data_all.zip')

In [26]:
data.head()

e    1    2    3    4    5    6    7    8    9   10   11   12   13   14  \
0  36.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2   3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  33.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  30.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

    15   16   17   18   19   20   21   22   23   24   25   26   27   28   29  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

    30   31   32   33   34   35   36   37   38   39   40   41   42   43   44  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  4.0  0.0  0.0  0.0  0.0   

    45   46   47   48   49   50   51   52   53   54   55   56   57   58   59  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

    60   61   62    63    64   65    66     67     68    69    70    71    72  \
0  0.0  0.0  0.0   0.0   0.0  0.0   0.0    0.0    0.0   4.0  21.0  37.0  37.0   
1  0.0  0.0  0.0   0.0   0.0  0.0   0.0    0.0    0.0   0.0   0.0   0.0   0.0   
2  0.0  1.0  7.0  32.0  32.0  9.0   5.0    4.0    4.0   4.0   4.0   2.0   0.0   
3  0.0  0.0  0.0   0.0   0.0  0.0   0.0    7.0   95.0  20.0   0.0   0.0   0.0   
4  0.0  0.0  0.0   0.0   0.0  0.0  18.0  107.0  108.0  18.0   0.0   0.0   0.0   

     73   74   75   76   77   78    79   80   81   82   83   84   85   86  \
0  21.0  3.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1   0.0  0.0  0.0  2.0  3.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2   0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3   0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4   0.0  0.0  0.0  0.0  0.0  4.0  16.0  6.0  0.0  0.0  0.0  0.0  0.0  0.0   

    87   88    89    90     91     92    93    94     95     96     97     98  \
0  0.0  0.0   0.0   0.0    0.0    0.0   0.0   1.0   20.0   50.0  115.0  172.0   
1  0.0  0.0   0.0   0.0    0.0    0.0   0.0   0.0    0.0    0.0    0.0    0.0   
2  0.0  0.0  10.0  34.0  112.0  112.0  51.0  39.0   37.0   37.0   37.0   32.0   
3  0.0  0.0   0.0   0.0    0.0    0.0   0.0   0.0   32.0  221.0   81.0    2.0   
4  0.0  0.0   0.0   0.0    0.0    0.0   0.0  20.0  152.0  194.0   36.0    0.0   

      99    100    101   102   103   104    105    106    107   108  109  110  \
0  215.0  215.0  170.0  78.0   7.0   0.0    0.0    0.0    0.0   0.0  0.0  0.0   
1    0.0    0.0    1.0   7.0  46.0  81.0  112.0   46.0   22.0   1.0  0.0  0.0   
2   21.0    4.0    2.0   0.0   0.0   0.0    0.0    0.0    0.0   0.0  0.0  0.0   
3    0.0    0.0    0.0   0.0   0.0   0.0    0.0    0.0    0.0   0.0  0.0  0.0   
4    0.0    0.0    0.0   0.0   0.0   0.0   18.0  110.0  157.0  88.0  7.0  0.0   

   111  112  113  114  115   116    117    118    119    120    121    122  \
0  0.0  0.0  0.0  0.0  0.0   0.0    0.0    0.0    0.0    0.0    1.0   35.0

In [8]:
data.shape

(116322, 785)

In [22]:
X = data.drop('e', axis = 1)
y = data['e']

print(f'X shape: {X.shape}\ny shape: {y.shape}')

X shape: (116322, 784)
y shape: (116322,)


In [58]:
y.sort_values().unique()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61.])

In [11]:
images = [np.array(row) for index, row in X.iterrows()]

In [12]:
images = [image.reshape(28,28) for image in images]

In [29]:
images[0].shape

(28, 28)

e:
   * 0 - 9 Number
   * 10 - 35 Upper
   * 36 - 61 lower

In [74]:
fig, axes = plt.subplots(10,10, figsize=(20,20))
for i,ax in enumerate(axes.flat):
    title = y[i]
    if title >= 36 and title <= 61:
        ax.imshow(images[i])
        ax.set_title(title)

In [102]:
y_upper = y.apply(lambda x: 1 if (x>=10) & (x <=35) else 0)
y_lower = y.apply(lambda x: 1 if (x>=35) & (x <=61) else 0)
y_number = y.apply(lambda x: 1 if (x>=0) & (x <=10) else 0)

In [121]:
def MultipleClassifiers(func, X, y, test_size = 0.2,):
    """ 
    Function that trains a model and return metrics
            
    :param X: data for training
    :param y: target values
    :param test_size: for trian _test_split(by default = .2)
    :return: accuracy, report and confusion matrix
    """
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, 
                                                        random_state=0)
    
    model = func
    print('Training... Go grab a coffee')
    clf = model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    acc = metrics.accuracy_score(y_test, y_pred)
    report = metrics.classification_report(y_test, y_pred)
    conf_m = metrics.confusion_matrix(y_test, y_pred)
    print('--------------------------------------------------------')
    print(f'Accuracy Score: {acc}')
    print('--------------------------------------------------------')
    print(report)
    print('--------------------------------------------------------')
    print('Cofusion Matix:')
    print(conf_m)
    
    return acc, report, conf_m

In [118]:
models = [
    LogisticRegression(),
    DecisionTreeClassifier(max_depth=5),
    KNeighborsClassifier(n_neighbors=5),
    GaussianNB()]

* Now, try to train a classifier model to predict the uppercases. Use every single model you know for classification.

In [126]:
for model in models:
        print(str(model))
        acc,report, conf_m = MultipleClassifiers(model,X, y_upper)
        print("*********************************\n*********************************")

LogisticRegression()
Training... Go grab a coffee


C:\Users\Emilio\anaconda3\envs\data\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


--------------------------------------------------------
Accuracy Score: 0.7475177304964539
--------------------------------------------------------
              precision    recall  f1-score   support

           0       0.77      0.93      0.84     17037
           1       0.56      0.26      0.35      6228

    accuracy                           0.75     23265
   macro avg       0.67      0.59      0.60     23265
weighted avg       0.72      0.75      0.71     23265

--------------------------------------------------------
Cofusion Matix:
[[15792  1245]
 [ 4629  1599]]
--------------------------------
DecisionTreeClassifier(max_depth=5)
Training... Go grab a coffee
--------------------------------------------------------
Accuracy Score: 0.7496668815817752
--------------------------------------------------------
              precision    recall  f1-score   support

           0       0.78      0.92      0.84     17037
           1       0.56      0.29      0.39      6228

    accur

#### Conlusions: 
1 = Upper<br>
0 = Non-Upper

   * Logistic:
        - 74.75% ratio of correct to incorrect preds (accuracy)
        - Decent at identifying 0 but bad at 1. (precision)
        - Good at finding all examples of 0 but bad at 1 (recall)
        
   * DecisionTreeClassifier:
        - 74.96% ratio of correct to incorrect preds (accuracy)
        - Decent at identifying 0 but bad at 1. (precision)
        - Good at finding all examples of 0 but bad at 1 (recall)
        
   * KNeighborsClassifier:
        - 85.64% ratio of correct to incorrect preds (accuracy)
        - Decent at identifying 0 but bad at 1. (precision)
        - V. Good at finding all examples of 0 but decent at 1 (recall)
        
   * GaussianNB:
        - 74.27% ratio of correct to incorrect preds (accuracy)
        - Decent at identifying 0 but bad at 1. (precision)
        - V.Good at finding all examples of 0 but really bad at 1 (recall)

* Try to do the same thing with lowercases.

In [127]:
# Your code here
for model in models:
        print(str(model))
        acc,report, conf_m = MultipleClassifiers(model,X, y_lower)
        print("*********************************\n*********************************")

LogisticRegression()
Training... Go grab a coffee


C:\Users\Emilio\anaconda3\envs\data\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


--------------------------------------------------------
Accuracy Score: 0.806662368364496
--------------------------------------------------------
              precision    recall  f1-score   support

           0       0.83      0.94      0.88     17752
           1       0.67      0.36      0.47      5513

    accuracy                           0.81     23265
   macro avg       0.75      0.65      0.68     23265
weighted avg       0.79      0.81      0.78     23265

--------------------------------------------------------
Cofusion Matix:
[[16757   995]
 [ 3503  2010]]
*********************************
*********************************
DecisionTreeClassifier(max_depth=5)
Training... Go grab a coffee
--------------------------------------------------------
Accuracy Score: 0.7892972275950999
--------------------------------------------------------
              precision    recall  f1-score   support

           0       0.82      0.93      0.87     17752
           1       0.60      0

#### Conlusions: 
1 = Upper<br>
0 = Non-Upper

   * Logistic:
        - 80.66% ratio of correct to incorrect preds (accuracy)
        - Good at identifying 0 but decent at 1. (precision)
        - Very Good at finding all examples of 0 but bad at 1 (recall)
        
   * DecisionTreeClassifier:
        - 78.92% ratio of correct to incorrect preds (accuracy)
        - Good at identifying 0 but bad at 1. (precision)
        - Very Good at finding all examples of 0 but really bad at 1 (recall)
        
   * KNeighborsClassifier:
        - 87.84% ratio of correct to incorrect preds (accuracy)
        - Very Good at identifying 0 and good at 1. (precision)
        - Very Good at finding all examples of 0 but bad at 1 (recall)
        
   * GaussianNB:
        - 26.92% ratio of correct to incorrect preds (accuracy)
        - Good at identifying 0 but really bad at 1. (precision)
        - Horrible at finding all examples of 0 and Excellent at 1 (recall)

* Try to do the same thing with numbers.

In [128]:
# Your code here
for model in models:
        print(str(model))
        acc,report, conf_m = MultipleClassifiers(model,X, y_number)
        print("*********************************\n*********************************")

LogisticRegression()
Training... Go grab a coffee


C:\Users\Emilio\anaconda3\envs\data\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


--------------------------------------------------------
Accuracy Score: 0.723318289275736
--------------------------------------------------------
              precision    recall  f1-score   support

           0       0.74      0.68      0.71     11429
           1       0.71      0.77      0.74     11836

    accuracy                           0.72     23265
   macro avg       0.72      0.72      0.72     23265
weighted avg       0.72      0.72      0.72     23265

--------------------------------------------------------
Cofusion Matix:
[[7748 3681]
 [2756 9080]]
*********************************
*********************************
DecisionTreeClassifier(max_depth=5)
Training... Go grab a coffee
--------------------------------------------------------
Accuracy Score: 0.7188050719965614
--------------------------------------------------------
              precision    recall  f1-score   support

           0       0.73      0.68      0.70     11429
           1       0.71      0.76 

#### Conlusions: 
1 = Upper<br>
0 = Non-Upper

   * Logistic:
        - 72.33% ratio of correct to incorrect preds (accuracy)
        - Decent at identifying 0 but decent at 1. (precision)
        - Decent at finding all examples of 0 and decent at 1 (recall)
        
   * DecisionTreeClassifier:
        - 71.88% ratio of correct to incorrect preds (accuracy)
        - decent at identifying 0 and decent at 1. (precision)
        - decent at finding all examples of 0 and decent at 1 (recall)
        
   * KNeighborsClassifier:
        - 87.58% ratio of correct to incorrect preds (accuracy)
        - Good at identifying 0 and good at 1. (precision)
        - Good at finding all examples of 0 and Very Good at 1 (recall)
        
   * GaussianNB:
        - 55.09% ratio of correct to incorrect preds (accuracy)
        - Decent at identifying 0 but really bad at 1. (precision)
        - Bad at finding all examples of 0 and Excellent at 1 (recall)

##### Overall:
- KNeighbors is the best.
- Gaussian are the worst.
- Logistic and Tree are regular.