# Supervised classification

In the data.csv there are letters (uppercases and lowercases) and numbers, 28x28 pixels in a row format.

* First, you need to know which labels are which, meaning you need to visualize some data to realize which number labels represents a letter, or a number.

In [35]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,plot_confusion_matrix,accuracy_score,balanced_accuracy_score,precision_score,recall_score,f1_score
from sklearn.naive_bayes import GaussianNB

In [2]:
# Your code here
df=pd.read_csv('data_all.zip')

In [59]:
df.head()

e    1    2    3    4    5    6    7    8    9  ...  775  776  777  778  \
0  36.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2   3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  33.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4  30.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

   779  780  781  782  783  784  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 785 columns]

In [5]:
df.dtypes

e      float64
1      float64
2      float64
3      float64
4      float64
        ...   
780    float64
781    float64
782    float64
783    float64
784    float64
Length: 785, dtype: object

In [7]:
df['e'].value_counts()

1.0     6330
7.0     6139
3.0     5969
2.0     5869
0.0     5778
        ... 
41.0     400
20.0     382
60.0     381
51.0     368
45.0     317
Name: e, Length: 62, dtype: int64

In [ ]:
#Labels: 1-9->1-9, 10-35->A-Z, 36-61->a-z

In [9]:
X=df[[x for x in df.columns if x!='e']]

In [10]:
y=df['e']

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=.20)

* Now, try to train a classifier model to predict the uppercases. Use every single model you know for classification.

In [12]:
# Your code here: primero se revisará el modelo "Decision Tree"
y_train_upper,y_test_upper=np.where((y_train>9) & (y_train<36),1,0),np.where((y_test>9) & (y_test<36),1,0)

In [15]:
classifier = DecisionTreeClassifier()

In [16]:
classifier.fit(X_train,y_train_upper)

DecisionTreeClassifier()

In [17]:
y_pred=classifier.predict(X_train)

In [18]:
y_pred_test=classifier.predict(X_test)

In [21]:
accuracy_score(y_train_upper,y_pred)

1.0

In [23]:
accuracy_score(y_test_upper,y_pred_test)

0.7369812375077909

In [24]:
balanced_accuracy_score(y_train_upper,y_pred)

1.0

In [25]:
balanced_accuracy_score(y_test_upper,y_pred_test)

0.6679102372568858

In [26]:
precision_score(y_train_upper,y_pred,average=None)

array([1., 1.])

In [27]:
precision_score(y_test_upper,y_pred_test,average=None)

array([0.82107347, 0.51263253])

In [28]:
recall_score(y_train_upper,y_pred,average=None)

array([1., 1.])

In [29]:
recall_score(y_test_upper,y_pred_test,average=None)

array([0.81800386, 0.51781662])

In [30]:
f1_score(y_train_upper,y_pred,average=None)

array([1., 1.])

In [31]:
f1_score(y_test_upper,y_pred_test,average=None)

array([0.81953579, 0.51521154])

In [32]:
confusion_matrix(y_train_upper,y_pred)

array([[17036,     0],
       [    0,  6228]], dtype=int64)

In [33]:
confusion_matrix(y_test_upper,y_pred_test)

array([[55576, 12365],
       [12111, 13006]], dtype=int64)

In [37]:
#Ahora se analizará el modelo "Naive Bayes Gaussian"
nb = GaussianNB()

In [38]:
nb.fit(X_train,y_train_upper)

GaussianNB()

In [39]:
y_pred=nb.predict(X_train)

In [40]:
y_pred_test=nb.predict(X_test)

In [41]:
accuracy_score(y_train_upper,y_pred)

0.7383081155433288

In [42]:
accuracy_score(y_test_upper,y_pred_test)

0.7346493584646134

In [43]:
balanced_accuracy_score(y_train_upper,y_pred)

0.5753641877874547

In [44]:
balanced_accuracy_score(y_test_upper,y_pred_test)

0.5713662587753888

In [45]:
precision_score(y_train_upper,y_pred,average=None)

array([0.76565078, 0.52633559])

In [46]:
precision_score(y_test_upper,y_pred_test,average=None)

array([0.76177909, 0.52027932])

In [47]:
recall_score(y_train_upper,y_pred,average=None)

array([0.92609768, 0.2246307 ])

In [48]:
recall_score(y_test_upper,y_pred_test,average=None)

array([0.92618596, 0.21654656])

In [49]:
f1_score(y_train_upper,y_pred,average=None)

array([0.83826577, 0.31487734])

In [50]:
f1_score(y_test_upper,y_pred_test,average=None)

array([0.83597595, 0.30581091])

In [51]:
confusion_matrix(y_train_upper,y_pred)

array([[15777,  1259],
       [ 4829,  1399]], dtype=int64)

In [52]:
confusion_matrix(y_test_upper,y_pred_test)

array([[62926,  5015],
       [19678,  5439]], dtype=int64)

* Try to do the same thing with lowercases.

In [53]:
# Your code here: modelo de Decision Tree
y_train_lower,y_test_lower=np.where(y_train>=36,1,0),np.where(y_test>=36,1,0)

In [54]:
classifier = DecisionTreeClassifier()

In [55]:
classifier.fit(X_train,y_train_lower)

DecisionTreeClassifier()

In [56]:
y_pred=classifier.predict(X_train)

In [57]:
y_pred_test=classifier.predict(X_test)

In [61]:
accuracy_score(y_train_lower,y_pred)

1.0

In [62]:
accuracy_score(y_test_lower,y_pred_test)

0.7684454856111242

In [63]:
balanced_accuracy_score(y_train_lower,y_pred)

1.0

In [64]:
balanced_accuracy_score(y_test_lower,y_pred_test)

0.6890165611629513

In [65]:
precision_score(y_train_lower,y_pred,average=None)

array([1., 1.])

In [66]:
precision_score(y_test_lower,y_pred_test,average=None)

array([0.85787202, 0.50087941])

In [67]:
recall_score(y_train_lower,y_pred,average=None)

array([1., 1.])

In [68]:
recall_score(y_test_lower,y_pred_test,average=None)

array([0.83720214, 0.54083098])

In [69]:
f1_score(y_train_lower,y_pred,average=None)

array([1., 1.])

In [70]:
f1_score(y_test_lower,y_pred_test,average=None)

array([0.84741106, 0.52008909])

In [71]:
confusion_matrix(y_train_lower,y_pred)

array([[17794,     0],
       [    0,  5470]], dtype=int64)

In [73]:
confusion_matrix(y_test_lower,y_pred_test)

array([[59834, 11635],
       [ 9913, 11676]], dtype=int64)

In [74]:
#Ahora se analizará el modelo "Naive Bayes Gaussian"
nb = GaussianNB()

In [75]:
nb.fit(X_train,y_train_lower)

GaussianNB()

In [76]:
y_pred=nb.predict(X_train)

In [77]:
y_pred_test=nb.predict(X_test)

In [78]:
accuracy_score(y_train_lower,y_pred)

0.33674346629986246

In [79]:
accuracy_score(y_test_lower,y_pred_test)

0.33942272561198394

In [80]:
balanced_accuracy_score(y_train_lower,y_pred)

0.549396947680123

In [81]:
balanced_accuracy_score(y_test_lower,y_pred_test)

0.5511246319885645

In [82]:
precision_score(y_train_lower,y_pred,average=None)

array([0.90730531, 0.25542678])

In [83]:
precision_score(y_test_lower,y_pred_test,average=None)

array([0.90555781, 0.25299444])

In [84]:
recall_score(y_train_lower,y_pred,average=None)

array([0.14797123, 0.95082267])

In [85]:
recall_score(y_test_lower,y_pred_test,average=None)

array([0.15616561, 0.94608365])

In [86]:
f1_score(y_train_lower,y_pred,average=None)

array([0.2544453 , 0.40267885])

In [87]:
f1_score(y_test_lower,y_pred_test,average=None)

array([0.26639139, 0.39922988])

In [88]:
confusion_matrix(y_train_lower,y_pred)

array([[ 2633, 15161],
       [  269,  5201]], dtype=int64)

In [90]:
confusion_matrix(y_test_lower,y_pred_test)

array([[11161, 60308],
       [ 1164, 20425]], dtype=int64)

* Try to do the same thing with numbers.

In [91]:
# Your code here: modelo de Decision Tree
y_train_number,y_test_number=np.where(y_train<=9,1,0),np.where(y_test<=9,1,0)

In [92]:
classifier = DecisionTreeClassifier()

In [93]:
classifier.fit(X_train,y_train_number)

DecisionTreeClassifier()

In [94]:
y_pred=classifier.predict(X_train)

In [95]:
y_pred_test=classifier.predict(X_test)

In [96]:
accuracy_score(y_train_number,y_pred)

1.0

In [97]:
accuracy_score(y_test_number,y_pred_test)

0.7488340604784113

In [98]:
balanced_accuracy_score(y_train_number,y_pred)

1.0

In [99]:
balanced_accuracy_score(y_test_number,y_pred_test)

0.7488090459905921

In [100]:
precision_score(y_train_number,y_pred,average=None)

array([1., 1.])

In [101]:
precision_score(y_test_number,y_pred_test,average=None)

array([0.74701984, 0.7507037 ])

In [102]:
recall_score(y_train_number,y_pred,average=None)

array([1., 1.])

In [103]:
recall_score(y_test_number,y_pred_test,average=None)

array([0.75538475, 0.74223334])

In [104]:
f1_score(y_train_number,y_pred,average=None)

array([1., 1.])

In [105]:
f1_score(y_test_number,y_pred_test,average=None)

array([0.75117901, 0.7464445 ])

In [106]:
confusion_matrix(y_train_number,y_pred)

array([[11698,     0],
       [    0, 11566]], dtype=int64)

In [107]:
confusion_matrix(y_test_number,y_pred_test)

array([[35281, 11425],
       [11948, 34404]], dtype=int64)

In [108]:
#Ahora se analizará el modelo "Naive Bayes Gaussian"
nb = GaussianNB()

In [109]:
nb.fit(X_train,y_train_number)

GaussianNB()

In [110]:
y_pred=nb.predict(X_train)

In [111]:
y_pred_test=nb.predict(X_test)

In [112]:
accuracy_score(y_train_number,y_pred)

0.5678731086657497

In [113]:
accuracy_score(y_test_number,y_pred_test)

0.5660985621870231

In [114]:
balanced_accuracy_score(y_train_number,y_pred)

0.5699033566144003

In [115]:
balanced_accuracy_score(y_test_number,y_pred_test)

0.5674702383165158

In [116]:
precision_score(y_train_number,y_pred,average=None)

array([0.74796503, 0.5379255 ])

In [117]:
precision_score(y_test_number,y_pred_test,average=None)

array([0.74342206, 0.53730952])

In [118]:
recall_score(y_train_number,y_pred,average=None)

array([0.21208754, 0.92771918])

In [119]:
recall_score(y_test_number,y_pred_test,average=None)

array([0.20688991, 0.92805057])

In [120]:
f1_score(y_train_number,y_pred,average=None)

array([0.33046953, 0.6809888 ])

In [121]:
f1_score(y_test_number,y_pred_test,average=None)

array([0.3236969 , 0.68058412])

In [122]:
confusion_matrix(y_train_number,y_pred)

array([[ 2481,  9217],
       [  836, 10730]], dtype=int64)

In [123]:
confusion_matrix(y_test_number,y_pred_test)

array([[ 9663, 37043],
       [ 3335, 43017]], dtype=int64)